version: '3'
services:
  postgres:
    image: postgres:15
    restart: always
    user: root
    environment:
      POSTGRES_PASSWORD: supersecret
# //     PG_USER: ${PG_USER}
#   /   PG_PASSWORD: ${PG_PASSWORD}
#      PG_DATABASE: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  app:
    build: .  # Build the combined image using the Dockerfile in the root
    env_file:
      - .env
    environment:
      OAUTH2_DOMAIN: ${OAUTH2_DOMAIN}
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      OAUTH2_TOKEN_URL: ${OAUTH2_TOKEN_URL}
      PG_USER: ${PG_USER}
      PG_HOST: ${PG_HOST}
      PG_DATABASE: ${PG_DATABASE}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
