apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: self-service-app
  template:
    metadata:
      labels:
        app: self-service-app
    spec:
      containers:
      - name: app
        image: your-dockerhub-username/self-service-app:latest
        env:
        - name: OAUTH2_DOMAIN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_DOMAIN
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_CLIENT_ID
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_CLIENT_SECRET
        - name: OAUTH2_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_TOKEN_URL
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_PASSWORD
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_DATABASE
        - name: PG_HOST
          value: postgres
        - name: PG_PORT
          value: "5432"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        ports:
        - containerPort: 3000
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: PG_DATABASE
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_CLIENT_ID
        - name: OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_CLIENT_SECRET
        - name: OAUTH2_TOKEN_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: OAUTH2_TOKEN_URL
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc